---
title: "R Notebook"
output: html_notebook
---


```{r}
#Operaciones Aritmeticas
3+5
8*5
5-1
(5 - 2) / 2
2 ^ 5
28 %% 6
```

```{r}
#Variables
x <- 10
y <- 15
total = x + y
total

mi_cadena <- "Mi texto"
mi_booleano <- FALSE

#Clase tipo de evento
class(mi_booleano)
class(mi_cadena)
```

```{r}
#Vectores
numericoVector <- c(1, 2, 3)
caracterVector <- c("a", "b", "c")
boleanoVector <- c(TRUE, FALSE, TRUE)
numericoVector
caracterVector
boleanoVector

some_vector <- c("John Doe", "poker player")
names(some_vector) <- c("Name", "Profesion")
some_vector

primer_vector <- c(140, -50, 20, -120, 240)
segundo_vector <- c(-24, -50, 100, -350, 10)

names(primer_vector) <- c("Lunes", "Martes", "Miercoles", "Jueves", "Viernes")

names(segundo_vector) <- c("Monday", "Tuesday", "Wednesday", "Thrsday", "Friday")

primer_vector
segundo_vector
```

```{r}
#Comparando y Seleccionando
edad <- 17
edad >= 18

vectorA <- c(1, 2, 3)
vectorB <- c(4, 5, 6)

totalVector <- vectorA + vectorB
totalVector

resultVector <- primer_vector + segundo_vector
resultVector

totalA <- sum(vectorA)
totalA

totalB <- sum(vectorB)
totalB

totalA + totalB

vectorB[2]
class(vectorB)

primer_vector[c(1,3,5)]

vectorMixto <- c("a", 2, FALSE, 3.5)
vectorMixto

primer_vector[2: 4]

result_primervector <- primer_vector[c("Martes", "Viernes")]
mean(result_primervector)

selectprimervector <- primer_vector > 0
selectprimervector

winprimervector <- primer_vector[selectprimervector]
winprimervector
```



```{r}
#Matrices

matrix(1:9, byrow=TRUE, nrow=3)
matrix(1:9, byrow=FALSE, nrow=3)

new_hope <- c(460.998, 314.4)
empire_strike <- c(2980.475, 247.900)
return_jedi <- c(309.306, 165.8)

box_office <- c(new_hope, empire_strike, return_jedi)

start_wars_matrix <- matrix(box_office, byrow = TRUE, nrow = 3)
start_wars_matrix

region <- c("US", "non-US")
titles <- c("A new Hope", "The Empire Strikes Back", "Return of the Jedi")

colnames(start_wars_matrix) <- region
rownames(start_wars_matrix) <- titles

start_wars_matrix
```
```{r}
#ROWSUMS()

worldwide_vector <- rowSums(start_wars_matrix)
worldwide_vector

all_wars_variable <- cbind(start_wars_matrix, worldwide_vector)
all_wars_variable

worldwide_cols <- colSums(all_wars_variable)
worldwide_cols

all_wars_variable <- rbind(all_wars_variable, worldwide_cols)
all_wars_variable

```

```{r}
#Selección de elementos en matrices

#non_us_all <- all_wars_variable[1:3,2]
#non_us_all <- all_wars_variable[ ,2]
#non_us_all <- all_wars_variable["A new Hope",2]

non_us_all <- all_wars_variable[1:3,2]
non_us_all

mean(non_us_all)
```

```{r}
#Aritmetica con matrices

us_all <- all_wars_variable[1:3, 1]
us_all
us_all <- us_all * 0.12
us_all

```

```{r}
#Factores

sex_vector <- c("Male", "Female", "Female", "Male", "Male")

factor_sex_vector <- factor(sex_vector)
factor_sex_vector


temperature_vector <- c("High", "Low", "High", "Low", "Medium")

factor_temperature_vector <- factor(temperature_vector, ordered = TRUE, levels = c("Low", "Medium", "High"))
factor_temperature_vector

```



