---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
sets <- read_csv('./DataSet/sets.csv')
themes <- read_csv('./DataSet/themes.csv')
parts <- read_csv('./DataSet/parts.csv')
part_categories <- read_csv('./DataSet/part_categories.csv')

```

```{r}

counties <- read_csv('./DataSet/counties.csv')
counties

counties %>%
  select(state, county, population, professional:production)

counties %>%
  select(state, county, population, ends_with('work'), starts_with('income'))

```

The rename verb
```{r}
counties %>%
  count(state) %>%
  rename(num_counties = n)

counties %>%
  select(state, county, poverty_rate=poverty)

```

using transmute
```{r}
counties %>%
  transmute(state, county, population, density=population/land_area) %>%
  filter(population > 1000000) %>%
  arrange(density)

```

```{r}
counties %>%
  rename(unemployment_reate = unemployment)

counties %>%
  select(state, county, contains('poverty'))

```

```{r}
counties %>%
  mutate(fraction_women = women/population)

counties %>%
  transmute(state, county, employment_rate = employed / population)

```

Joining Data with dplyr
```{r}
#View(sets)
sets
themes
```

```{r}
sets %>%
  inner_join(themes, by=c("theme_id" = "id"))
```


```{r}
view(parts)
view(part_categories)

view_parts <- parts %>%
  inner_join(part_categories, by = c("part_cat_id" = "id"))
view(view_parts)

view_parts <- parts %>%
  inner_join(part_categories, by = c("part_cat_id" = "id"), suffix = c("_parts", "_parts_categories"))
view(view_parts)

```



