---
title: "R Notebook"
output: html_notebook
---

Introduction to the Tidyverse
```{r}
library(gapminder)
library(dplyr)

gapminder
```

Filtering
```{r}
gapminder %>% filter(year == 1957)
```

Arrage
```{r}
gapminder %>% arrange(lifeExp)
gapminder %>% arrange(desc(lifeExp))
```


Firletring and Arraging
```{r}
gapminder %>% filter(year==1957) %>% arrange(desc(pop))
```

The verb mutate
```{r}
gapminder %>% mutate(lifeExp = lifeExp * 12)
gapminder %>% mutate(lifeExpMonths = lifeExp * 12)
```


Combining filter, mutate and arrange
```{r}
gapminder %>%
  filter(year == 2007) %>%
  mutate(lifeExpMounth = lifeExp * 12) %>%
  arrange(desc(lifeExpMounth))

```

```{r}
library(ggplot2)

gapminder_1952 <- gapminder %>% filter(year == 1952 & continent == "Asia")
gapminder_1952 <- gapminder %>% filter(year == 1952)
gapminder_1952

ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) + geom_point()

```


Log Scaling
```{r}
ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) + geom_point() + scale_x_log10()
ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) + geom_point() + scale_x_log10() + scale_y_log10()
```

Variable categorica
```{r}
ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent)) + geom_point() + scale_x_log10() + scale_y_log10()


```



