---
title: "R Notebook"
output: html_notebook
---


functions
```{r}
pow_two <- function(x, print_info=TRUE){
  y <- x ^ 2
  if (print_info) {
    print(paste(x, " to the power two equals ", y))
  }
  return (y)
}

result = pow_two(3)
result
```


Function Scoping
```{r}
pow_two <- function(x, print_info=TRUE){
  y <- x ^ 2
  return (y)
}

pow_two(5)

```


R passes arguments by value
```{r}
triple <- function(x){
  x <- 3^x
  return(x)
}

a <- 2
triple(a)
a
```

Other type of parameters
```{r}
linkedin <- c(16,9,13,5,2,17,14)

interpret <- function(num_views){
  if (num_views > 15) {
    print("You´re popular!")
    return(num_views)
  }else{
    print("Try to be more visible!")
    return(0)
  }
}

interpret(linkedin[1])

interpret_all <- function(views, return_sum=TRUE){
  
  count <- 0
  
  for (item in views) {
    count <- count + interpret(item)
  }
  
  if (return_sum) {
    return(count)
  }else{
    return(NULL)
  }
}

interpret_all(linkedin)

```

Load an R Package
```{r}
library(ggplot2)

qplot(mtcars$wt, mtcars$hp)

```


Use Apply with R
```{r}
temp <- list(c(3,7,9,6,1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2), c(5,7,9,4,2), c(-3,5,8,9,4), c(3,6,9,4,1))

select <- function(x, index){
  print(paste("this collection contains total = ", sum(x)))
}

list <- lapply(temp, select)

class(list)

#for (t in temp) {
#  print(min(t))
#}

```

lapply and anonymous functions

```{r}
(function(x) { 3 * x })(9)

pioneers <- c("GAUSS:1777", "BAYES:1702", "PASCAL:1623","PEARSON:1857")
split <- strsplit(pioneers, ":")

split_low <- lapply(split, tolower)
split_low

names <- lapply(split_low, function(x){ x[1]})
names

years <- lapply(split_low, function(x){ x[2]})
years


```

use lapply with additional arguments
```{r}
select_el <- function(x, index){
  x[index]
}

names <- lapply(split_low, select_el, 1)
names

years <- lapply(split_low, select_el, 2)
years

```

sapply
```{r}
extremes <- function(x){
  c(min=min(x), max=max(x))
}

lapply(temp, extremes)
sapply(temp, extremes)

temp2 <- list(1,2,3,4,5)
temp2

funct_temp2 <- function(x){
  x
}

lapply(temp2, funct_temp2)
sapply(temp2, funct_temp2)

```

vapply
```{r}
basics <- function(x){
  c(min=min(x), mean=mean(x), max= max(x))
}

lapply(temp, basics)
sapply(temp, basics)
vapply(temp, basics, numeric(3))

temp3 <- c("Guatemala", "Salvador", "Honduras", "Nicaragua")
nchar(temp3)

unique_letters <- function(name){
  bane <- gsub(" ", "", name)
  letters <- strsplit(name, split="")[[1]]
  unique(letters)
}

lapply(temp3, unique_letters)
sapply(temp3, unique_letters)
vapply(temp3, unique_letters, nchar(7))
```

utilities
```{r}
errors <- c(1.9, -2.6, 4.0, -9.5, -3.4, 7.3)
print(sum(abs(round(errors))))

?sum

linkedin <- list(16, 9, 13, 5, 2, 17, 14)
facebook <- list(17, 7, 5, 16, 8, 13, 14)

li_vec <- unlist(linkedin)
fb_vec <- unlist(facebook)

li_vec
fb_vec

social_vec <- append(li_vec,fb_vec)
social_vec

sort(social_vec, decreasing = TRUE)
sort(social_vec)

```

grep & grepl
```{r}
emails <- c("john.doe@ivyleague.edu", "education@world.gov", "dalai.lama@peace.org",
            "invalid.edu", "quant@bigdatacollege.edu", "cookie.monster@sesame.tv")

grepl(pattern = "edu", x = emails)

hits <- grep(pattern = "edu", x = emails)
emails[hits]
```

