---
title: "R Notebook"
output: html_notebook
---

Intermediate R

```{r}
3 == (2 + 1)
"intermediate" != "r"
TRUE != FALSE
"Rchitect" != "rchitect"

```

Greater and less than
```{r}
-6 * 5 + 2 >= -10 + 1

"raining" <= "table"

TRUE > FALSE
TRUE < FALSE

"@" >= "?"

"a" < "A"

```

Compare vectors and matrix
```{r}
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
facebook <- c(17, 7, 5, 16, 8, 13, 14)

linkedin > 15
facebook <= 10

linkedin > facebook

views <- matrix(c(linkedin, facebook), nrow = 2, byrow = TRUE)
views

views == 13
views <= 14

```

Operators logical
```{r}
linkedin <= 10 & facebook == 13
linkedin <= 10 | facebook == 13

views > 11 & views <= 14
```

Statement IF
```{r}
medium <- "Linkedin"
num_views <- 20

if (medium == "Linkedin") {
  print("Showing LinkedIn information")
} else {
  print("Unknown medium")
}

if (num_views > 15) {
  print("You´re popular!")
} else {
  print("Try to be more visible!")
}

```

Customize statement IF
```{r}
medium <- "Facebook"

if (medium == "Linkedin") {
  print("Showing LinkedIn information")
} else if (medium == "Facebook") {
  print("Show Facebook information")
} else {
  print("Unknown medium")
}

```


Else if 2.0
```{r}
number = 1
result = ""

if (number < 10) {
    if (number < 5) {
      result <- "extra small"
    } else {
      result <- "small"
    }
} else if (number < 100) {
  result <- "medium"
} else {
  result <- "large"
}

print(result)

```



Loops
```{r}
spped <- 64

while (spped > 30){
  print(paste("Your speed is ", spped))
  
  if (spped >= 48) {
    print("Slow down big time!")
    spped <- spped - 11
  }else{
    print("Slow down!")
    spped <- spped - 6
  }
}

spped
```


Break
```{r}
spped <- 88

while (spped > 30){
  print(paste("Your speed is ", spped))
  
  if (spped > 80) {
    break
  }else if(speed > 48){
    print("Slow down big time!")
    spped <- spped - 11
  }else{
    print("Slow down!")
    spped <- spped - 6
  }
}

spped
```


For loop
```{r}
linkedin <- c(16, 9, 13, 5, 2, 17, 14)

for (item in linkedin) {
  print(item)
}

for (i in 1:length(linkedin)){
  print(linkedin[i])
}

for (i in 1:length(linkedin)){
  print(paste(i, " - ", linkedin[i]))
}

```


Loop over a list
```{r}
nyc <- list(pop=84058337, boroughs = c("Manhattan", "Bronx", "Brooklyn", "Queens", "Staten Island"), capital=FALSE)

for (n in nyc) {
  print(n)
}

for (i in 1:length(nyc)) {
  if (i == 2) {
    for (j in 1:length(nyc[[i]])) {
      print(nyc[[i]][j])
    }
  }else{
    print(nyc[[i]])
  }
}

```

Loop over a matrix
```{r}
views <- matrix(c(linkedin, facebook), nrow = 2, byrow = TRUE)

for (row in 1:nrow(views)) {
  for (col in 1:ncol(views)) {
    print(paste("On row ", row, " and column ", col, " contains ", views[row, col]))
  }
}
```


